### ISSUE TITLE
Old Song List - Creative Genres messing up

### ISSUE THREAD

**Issue by thumbapprentice** [KatieFrogs/taiko-web-plugins#4]
Recently I just saw that if you load the Old Song List Plugin when you're on the Official Song List Page, then disable it, move to Creative Song List, Genres get messed up.

For example,
Variety gets moved to "Kids"
![Screenshot 2022-03-25 13 22 08](https://user-images.githubusercontent.com/99283853/160195765-82c8fe36-f2db-4cad-bba6-a482e48007e1.png)

and Game Music gets moved to "Classical"
![Screenshot 2022-03-25 13 21 54](https://user-images.githubusercontent.com/99283853/160195816-1ab0aeca-90c3-48c4-8dc4-b534831de71f.png)

**Comment by KatieFrogs** [comment]
Thanks, fixed in 08df431

You will need to update the plugin: [**Old Song List**](https://github.com/KatieFrogs/taiko-web-plugins/raw/main/old-song-list.taikoweb.js) [(⬇️)](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/KatieFrogs/taiko-web-plugins/raw/main/old-song-list.taikoweb.js)
